// lib/features/tap_to_pay/presentation/merchant_receive_screen.dart

import 'package:flutter/material.dart';
import 'dart:typed_data';
import 'package:cryptography/cryptography.dart';

import '../hardware/nfc_service.dart';
import '../../../core/protocol/offline_protocol.dart';
import '../../../core/protocol/transaction_payload.dart';
import '../../../core/database/database_schema.dart';
import '../../sync_ledger/bloc/sync_cubit.dart';
import 'package:cbor/cbor.dart';
import 'package:flutter_bloc/flutter_bloc.dart';


class MerchantReceiveScreen extends StatefulWidget {
  final AppDatabase database;
  const MerchantReceiveScreen({Key? key, required this.database}) : super(key: key);
  @override
  State<MerchantReceiveScreen> createState() => _MerchantReceiveScreenState();
}

class _MerchantReceiveScreenState extends State<MerchantReceiveScreen> {
  final NfcService _nfcService = NfcService();
  final OfflineProtocol _protocol = OfflineProtocol();

  String _statusMessage = 'Enter amount and tap "Start POS"';
  bool _isScanning = false;
  bool _paymentSuccess = false;

  // For testing, we mock the customer's registered public key.
  // In production, the merchant's DB has this from the backend sync,
  // or it is passed inside the CBOR payload (which requires larger APDU frames).
  late SimplePublicKey _mockCustomerPublicKey;

  @override
  void initState() {
    super.initState();
    _setupMockKey();
  }





  Future<void> _setupMockKey() async {
    // Generates a mock keypair just so the verifier has a valid format to check against.
    // To do a real end-to-end crypto test today, you will need to hardcode the
    // exact public key bytes generated by the Customer app.
    final ed25519 = Ed25519();
    final pair = await ed25519.newKeyPair();
    _mockCustomerPublicKey = await pair.extractPublicKey();
  }

  void _startScanning() async {
    setState(() {
      _isScanning = true;
      _statusMessage = 'Waiting for customer phone...';
      _paymentSuccess = false;
    });

    await _nfcService.startMerchantReader(
      onPayloadReceived: (Uint8List payload) async {
        setState(() {
          _statusMessage = 'Payload received! Verifying signature...';
        });

        await _processIncomingPayment(payload);
      },
      onError: (String error) {
        setState(() {
          _isScanning = false;
          _statusMessage = 'Error: $error';
        });
      },
    );
  }

  Future<void> _processIncomingPayment(Uint8List fullPayload) async {
    try {
      if (fullPayload.length < 64) throw Exception("Payload too small.");

      // 1. Split the payload
      final cborBytesLength = fullPayload.length - 64;
      final cborBytes = fullPayload.sublist(0, cborBytesLength);
      final signatureBytes = fullPayload.sublist(cborBytesLength);

      // 2. Verify Cryptography first (Zero-Trust)
      final isValid = await _protocol.verifyMerchantReceipt(
        receiptCborBytes: cborBytes,
        signatureBytes: signatureBytes,
        merchantPublicKey: _mockCustomerPublicKey,
      );

      setState(() {
        _isScanning = false;
      });

      if (isValid) {
        // 3. Decode the CBOR payload dynamically
        final cborValue = cbor.decode(cborBytes);
        final payloadMap = cborValue.toObject() as Map;

        final decodedWalletId = payloadMap['walletId'] as int? ?? 1;
        final decodedAmountMinor = payloadMap['amountMinor'] as int? ?? 5000;

        // Convert minor units (paise) to major units (Rupees) for the UI
        final displayAmount = (decodedAmountMinor / 100).toStringAsFixed(2);

        // 4. Save the real, dynamic data to the Drift Ledger
        await widget.database.commitOfflineTransaction(
          walletId: decodedWalletId,
          deductionAmount: decodedAmountMinor,
          transactionId: 'txn_${DateTime.now().millisecondsSinceEpoch}',
          cborPayload: cborBytes,
          signature: signatureBytes,
          encryptedJournal: Uint8List(0),
        );

        setState(() {
          _paymentSuccess = true;
          // Dynamically show the exact amount received!
          _statusMessage = 'Success! Received ₹$displayAmount from Wallet #$decodedWalletId';
        });
      } else {
        setState(() {
          _statusMessage = 'FRAUD ALERT: Invalid cryptographic signature.';
        });
      }
    } catch (e) {
      setState(() {
        _isScanning = false;
        _statusMessage = 'Validation failed: $e';
      });
    }
  }

  @override
  @override
  Widget build(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;

    return Scaffold(
      appBar: AppBar(
        title: const Text('Merchant POS'),
        // Add a subtle gradient line under the app bar
        bottom: PreferredSize(
          preferredSize: const Size.fromHeight(1.0),
          child: Container(
            color: colorScheme.primary.withOpacity(0.2),
            height: 1.0,
          ),
        ),
      ),

        // Replace your floatingActionButton with this:
        floatingActionButton: StreamBuilder<List<PendingLedgerData>>(
          stream: widget.database.select(widget.database.pendingLedger).watch(),
          builder: (context, snapshot) {
            final pendingCount = snapshot.data?.length ?? 0;

            if (pendingCount == 0) return const SizedBox.shrink();

            return BlocConsumer<SyncCubit, SyncState>(
              listener: (context, syncState) {
                if (syncState is SyncSuccess) {
                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(content: Text('Successfully synced ${syncState.count} transactions!'), backgroundColor: Colors.green),
                  );
                } else if (syncState is SyncFailure) {
                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(content: Text('Sync failed: ${syncState.error}'), backgroundColor: Colors.red),
                  );
                }
              },
              builder: (context, syncState) {
                final isSyncing = syncState is SyncInProgress;

                return FloatingActionButton.extended(
                  onPressed: isSyncing ? null : () => context.read<SyncCubit>().runCloudSync(),
                  backgroundColor: isSyncing ? Colors.grey : colorScheme.primary,
                  elevation: 8,
                  icon: isSyncing
                      ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
                      : const Icon(Icons.cloud_upload, color: Colors.black87),
                  label: Text(
                      isSyncing ? 'Syncing...' : 'Sync $pendingCount Offline Taps',
                      style: const TextStyle(color: Colors.black87, fontWeight: FontWeight.bold)
                  ),
                );
              },
            );
          },
        ),
           // Hide the button completely if there's nothing to sync (cleaner UI)

      body: Column(
        children: [
          // -----------------------------------------
          // TOP HALF: The Sleek POS Scanner
          // -----------------------------------------
          Container(
            width: double.infinity,
            padding: const EdgeInsets.symmetric(vertical: 40.0, horizontal: 24.0),
            decoration: BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment.topCenter,
                end: Alignment.bottomCenter,
                colors: [
                  colorScheme.surface.withOpacity(0.5),
                  Colors.transparent,
                ],
              ),
            ),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                // Glowing Status Icon
                Container(
                  padding: const EdgeInsets.all(24),
                  decoration: BoxDecoration(
                    shape: BoxShape.circle,
                    color: _paymentSuccess
                        ? colorScheme.secondary.withOpacity(0.1)
                        : (_isScanning ? colorScheme.primary.withOpacity(0.1) : Colors.white10),
                    boxShadow: _isScanning || _paymentSuccess ? [
                      BoxShadow(
                        color: _paymentSuccess ? colorScheme.secondary.withOpacity(0.3) : colorScheme.primary.withOpacity(0.3),
                        blurRadius: 30,
                        spreadRadius: 10,
                      )
                    ] : [],
                  ),
                  child: Icon(
                    _paymentSuccess ? Icons.check_circle : (_isScanning ? Icons.sensors : Icons.contactless),
                    size: 70,
                    color: _paymentSuccess ? colorScheme.secondary : (_isScanning ? colorScheme.primary : Colors.white54),
                  ),
                ),
                const SizedBox(height: 24),
                Text(
                  _statusMessage,
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.w600,
                    color: _paymentSuccess ? colorScheme.secondary : Colors.white,
                  ),
                ),
                const SizedBox(height: 32),
                if (!_isScanning)
                  ElevatedButton(
                    onPressed: _startScanning,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: colorScheme.primary,
                      foregroundColor: Colors.black,
                      padding: const EdgeInsets.symmetric(horizontal: 40, vertical: 16),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(30)),
                      elevation: 5,
                    ),
                    child: const Text('ACTIVATE SCANNER', style: TextStyle(fontSize: 16, letterSpacing: 1.2, fontWeight: FontWeight.bold)),
                  ),
              ],
            ),
          ),

          // -----------------------------------------
          // BOTTOM HALF: Modern Fintech Ledger
          // -----------------------------------------
          Expanded(
            child: Container(
              decoration: BoxDecoration(
                color: colorScheme.surface,
                borderRadius: const BorderRadius.only(topLeft: Radius.circular(30), topRight: Radius.circular(30)),
                border: Border.all(color: Colors.white.withOpacity(0.05)),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Padding(
                    padding: const EdgeInsets.only(left: 24, top: 24, bottom: 8),
                    child: Text(
                      'Offline Ledger',
                      style: TextStyle(fontSize: 14, letterSpacing: 1.5, fontWeight: FontWeight.bold, color: Colors.white.withOpacity(0.5)),
                    ),
                  ),
                  Expanded(
                    child: StreamBuilder<List<PendingLedgerData>>(
                      stream: widget.database.select(widget.database.pendingLedger).watch(),
                      builder: (context, snapshot) {
                        if (snapshot.connectionState == ConnectionState.waiting) {
                          return const Center(child: CircularProgressIndicator());
                        }

                        if (!snapshot.hasData || snapshot.data!.isEmpty) {
                          return Center(
                            child: Column(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                Icon(Icons.receipt_long, size: 48, color: Colors.white.withOpacity(0.1)),
                                const SizedBox(height: 16),
                                Text('No pending transactions', style: TextStyle(color: Colors.white.withOpacity(0.3))),
                              ],
                            ),
                          );
                        }

                        final transactions = snapshot.data!;

                        return ListView.builder(
                          padding: const EdgeInsets.only(top: 8, bottom: 80),
                          itemCount: transactions.length,
                          itemBuilder: (context, index) {
                            final tx = transactions[index];
                            final timeString = tx.createdAt.toString().split('.')[0].substring(11, 16);

                            // Premium Card Design
                            return Container(
                              margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 6),
                              decoration: BoxDecoration(
                                color: const Color(0xFF0F172A),
                                borderRadius: BorderRadius.circular(16),
                                border: Border.all(color: Colors.white.withOpacity(0.05)),
                              ),
                              child: ListTile(
                                contentPadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 8),
                                leading: Container(
                                  padding: const EdgeInsets.all(10),
                                  decoration: BoxDecoration(
                                    color: Colors.amber.withOpacity(0.1),
                                    borderRadius: BorderRadius.circular(12),
                                  ),
                                  child: const Icon(Icons.bolt, color: Colors.amber),
                                ),
                                title: Text('Wallet #${tx.walletId}', style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                                subtitle: Text('Txn: ${tx.transactionId.substring(0, 8)}...', style: TextStyle(color: Colors.white.withOpacity(0.5), fontSize: 13)),
                                trailing: Column(
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  crossAxisAlignment: CrossAxisAlignment.end,
                                  children: [
                                    const Text('Unsynced', style: TextStyle(color: Colors.amber, fontWeight: FontWeight.bold)),
                                    const SizedBox(height: 4),
                                    Text(timeString, style: TextStyle(color: Colors.white.withOpacity(0.4), fontSize: 12)),
                                  ],
                                ),
                              ),
                            );
                          },
                        );
                      },
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}